// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7gigBqVC1ureaKNnHsBUNZMKPXWy1C8',
    appId: '1:938535556878:web:c577bc5ecc52bdc2d3e95f',
    messagingSenderId: '938535556878',
    projectId: 'midsem-fa245',
    authDomain: 'midsem-fa245.firebaseapp.com',
    storageBucket: 'midsem-fa245.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkx94ivD08I3-j2KQ7SuAsk6vYGi4XtU',
    appId: '1:938535556878:android:26c90617f7433819d3e95f',
    messagingSenderId: '938535556878',
    projectId: 'midsem-fa245',
    storageBucket: 'midsem-fa245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjBihPoBK35Ib_Ae-lC69nekQ_8BllYBk',
    appId: '1:938535556878:ios:da31c5908e6b059bd3e95f',
    messagingSenderId: '938535556878',
    projectId: 'midsem-fa245',
    storageBucket: 'midsem-fa245.appspot.com',
    iosBundleId: 'com.example.homeWork3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjBihPoBK35Ib_Ae-lC69nekQ_8BllYBk',
    appId: '1:938535556878:ios:2e5bc8e51715a499d3e95f',
    messagingSenderId: '938535556878',
    projectId: 'midsem-fa245',
    storageBucket: 'midsem-fa245.appspot.com',
    iosBundleId: 'com.example.homeWork3.RunnerTests',
  );
}
